### Logistic Regression

In [12]:
import numpy as np
import pandas as pd
import seaborn as sns

In [14]:
df = pd.read_csv('F:/DATA ANALYSIS/Machine Learnig/Complete Machine Learning with Python/Data Files/2. ST Academy - Classification models resource files/Classification preprocessed data Python.csv',header=0)
df.head()


price  resid_area  air_qual  room_num   age  teachers  poor_prop  \
0   24.0       32.31     0.538     6.575  65.2      24.7       4.98   
1   21.6       37.07     0.469     6.421  78.9      22.2       9.14   
2   34.7       37.07     0.469     7.185  61.1      22.2       4.03   
3   33.4       32.18     0.458     6.998  45.8      21.3       2.94   
4   36.2       32.18     0.458     7.147  54.2      21.3       5.33   

   n_hos_beds  n_hot_rooms  rainfall     parks  Sold  avg_dist  airport_YES  \
0       5.480     11.19200        23  0.049347     0    4.0875            1   
1       7.332     12.17280        42  0.046146     1    4.9675            0   
2       7.394     46.19856        38  0.045764     0    4.9675            0   
3       9.268     11.26720        45  0.047151     0    6.0650            1   
4       8.824     11.28960        55  0.039474     0    6.0625            0   

   waterbody_Lake  waterbody_Lake and River  waterbody_River  
0               0                         0                1  
1               1                         0                0  
2               0                         0                0  
3               1                         0                0  
4               1                         0                0

In [16]:
X = df[['price']]

In [18]:
y= df['Sold']

In [20]:
X.head()

price
0   24.0
1   21.6
2   34.7
3   33.4
4   36.2

In [22]:
y.head()

0    0
1    1
2    0
3    0
4    0
Name: Sold, dtype: int64

In [26]:
from sklearn.linear_model import LogisticRegression

In [28]:
clf_lrs =  LogisticRegression()

In [30]:
clf_lrs.fit(X,y)

LogisticRegression()

In [32]:
clf_lrs.coef_

array([[-0.03571865]])

In [34]:
clf_lrs.intercept_

array([0.61477516])

In [40]:
import statsmodels.api as sn

In [42]:
X_cons = sn.add_constant(X)

In [44]:
X_cons .head()

const  price
0    1.0   24.0
1    1.0   21.6
2    1.0   34.7
3    1.0   33.4
4    1.0   36.2

In [46]:
import statsmodels.discrete.discrete_model as sm

In [48]:
logit = sm.Logit(y,X_cons).fit()

Optimization terminated successfully.
         Current function value: 0.676690
         Iterations 5


In [50]:
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  506
Model:                          Logit   Df Residuals:                      504
Method:                           MLE   Df Model:                            1
Date:                Sat, 28 Dec 2024   Pseudo R-squ.:                 0.01788
Time:                        13:10:31   Log-Likelihood:                -342.41
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                 0.0004142
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.6149      0.248      2.484      0.013       0.130       1.100
price         -0.0357      0.010     -3.417      0.001      -0.056      -0.015
==============================================================================
"""

### Logistic Regression with muliple predictor

In [53]:
X = df.loc[ : ,df.columns != 'Sold']

In [55]:
y = df['Sold']

In [59]:
clf_lr =  LogisticRegression()
clf_lr.fit(X,y)

C:\Users\Mazy\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [61]:
clf_lr.coef_

array([[-0.24634735, -0.01729779, -0.11019251,  0.86254123, -0.00599827,
         0.22821435, -0.21020497,  0.18007816, -0.09088539, -0.00705128,
        -0.00499199, -0.32611796, -0.10520939, -0.0948627 , -0.01512222,
         0.20178678]])

In [63]:
clf_lr.intercept_

array([0.01671003])

In [ ]:
X_cons = sn.add_constant(X)
