## NUMPY

In [1]:
import numpy as np

In [ ]:
np1 = np.array([1,2,3,4,5,6])  # 1d
np1

array([1, 2, 3, 4, 5, 6])

In [4]:
type(np1)

numpy.ndarray

In [6]:
mat = np.array([[1,2],[3,4]])  # 2d
mat

array([[1, 2],
       [3, 4]])

In [7]:
np1.shape

(6,)

In [8]:
mat.shape

(2, 2)

In [9]:
mat.dtype

dtype('int64')

In [13]:
mat[0,0]= 5

In [14]:
mat

array([[5, 2],
       [3, 4]])

In [15]:
mat[0,0]= 'max'

ValueError: invalid literal for int() with base 10: 'max'

In [16]:
mat1 = np.arange(0,10,1)

In [17]:
mat1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
mat2 = np.linspace(0,5,10)
mat2

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [19]:
mat2.shape

(10,)

In [21]:
mat3 = np.random.randint(0,10)

In [22]:
mat3

5

In [23]:
mat4 = np.random.rand(3,3)

In [24]:
mat4

array([[0.98898432, 0.7704925 , 0.95863574],
       [0.13126731, 0.25955583, 0.47466608],
       [0.57697675, 0.22903277, 0.756337  ]])

In [25]:
mat5 = np.random.randn(3,3)

In [26]:
mat5

array([[-2.41269714e-01,  4.19172629e-04,  1.22841562e+00],
       [-6.82066509e-02,  9.62214356e-01, -6.05706529e-01],
       [-1.27809117e+00,  2.07598056e-01, -8.25868151e-01]])

In [43]:
m = np.diag(mat5) # retrive diagonal elements of an matrix
n = np.zeros(10)
o = np.ones((2,3))

print(m)
print(n)
print(o)

[-0.24126971  0.96221436 -0.82586815]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [37]:
m

<function diag at 0x00000250A8596170>

In [40]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])